Feature/create user profile service
Inunor/internship pull request #111
Opened 2021-07-23 12:56 UTC by tanyushanel

2021-07-25 13:55 UTC, Inunor requested changes

2021-07-25 13:55 UTC, Inunor commented on src/app/models/user-profile/user-profile.component.ts
> +      this.testHttpService.getTestResults(userId).subscribe((tests: Test[]) => {
As I understand you would use this.results inside html file. You shouldn't make it that way. You can type results | async inside your html file, plus I think it is better to have testHttpStoreService as well. As we discussed -> httpService and storeService comes together

2021-07-25 13:55 UTC, Inunor commented on src/app/models/user-profile/user-profile.component.ts
> +      this.testHttpService.getTestResults(userId).subscribe((tests: Test[]) => {
This setTestResults should be insde TestStoreHttpService

2021-07-29 05:28 UTC, Inunor commented
Any progress or do you have a problem with this pr?

2021-08-03 10:07 UTC, RomPavel commented on src/constants/route-constant.ts
> +export const BASE_API_URL = 'http://elevel-001-site1.btempurl.com';
Please reuse this variable in LoginApiUrl and  RefreshUserDataUrl

2021-08-03 10:07 UTC, RomPavel commented on src/constants/mock-test-results.ts
> +// export function createNewTestResult(id: number): Test {
please remove all mocks if you dont need them

2021-08-03 10:10 UTC, RomPavel commented on src/app/models/user-profile/user-profile.component.ts
> +    this.testStoreService.getTestResults().subscribe({
It should be in another way, as @Inunor proposed.
You just call this.testStoreService.getTestResults() here, but in testStoreService you subscribe to result and store result in a Observable variable (fox example **testsResults$**). And in this component you use **testsResults$**

2021-08-03 10:10 UTC, RomPavel commented on src/app/models/user-profile/user-profile.component.ts
> +    // this.results$ = [...MOCK_TEST_RESULTS];
Please remove all the comments

2021-08-03 10:15 UTC, tanyushanel commented on src/app/models/user-profile/user-profile.component.ts
> +    this.testStoreService.getTestResults().subscribe({
I tried? but have no idea how to use observable as matdatasourse.

2021-08-03 10:19 UTC, RomPavel commented
> Done without observables$ | async in templates cos have no idea how to use observables as matdatasource. Had tried, but didn't have a result.
> Services for test are done as global considering to reuse them in other modules.
> There is a hard-coded userId in service just to show receiving results from server. Will be removed.


Did you try this?
![image](https://user-images.githubusercontent.com/31888768/127999805-bcd2cf5c-a231-4227-b002-25b6a310725f.png)

2021-08-03 10:35 UTC, RomPavel commented on src/app/models/user-profile/user-profile.component.ts
> +    this.testStoreService.getTestResults().subscribe({
> > Done without observables$ | async in templates cos have no idea how to use observables as matdatasource. Had tried, but didn't have a result.
> > Services for test are done as global considering to reuse them in other modules.
> > There is a hard-coded userId in service just to show receiving results from server. Will be removed.
> 
> Did you try this?
> ![image](https://user-images.githubusercontent.com/31888768/127999805-bcd2cf5c-a231-4227-b002-25b6a310725f.png)

2021-08-03 12:12 UTC, tanyushanel commented on src/app/models/user-profile/user-profile.component.ts
> +    this.testStoreService.getTestResults().subscribe({
![image](https://user-images.githubusercontent.com/60880817/128013116-49ecab78-0078-49a0-9dbc-a219e5aeb182.png)
Seems like a magic-stick. Zzzz...

2021-08-03 12:18 UTC, RomPavel commented on src/app/models/user-profile/user-profile.component.ts
> +    this.results$ = this.testStoreService.getTestResults();
its still not in a proper way.
getTestResults() should not really return anything.
you should have testResults$ variable in your store service and getTestResults should set new value of  testResults$

2021-08-03 14:20 UTC, RomPavel commented on src/app/services/test/test/test-store.service.ts
> +  setTestResults(): void {
I would stick with getTestResults. Meaning of get in naming is not like 'get result of this function' but more like 'get tests results from backend'

2021-08-03 14:20 UTC, RomPavel approved these changes

2021-08-03 15:10 UTC, Inunor approved these changes

2021-08-03 15:54 UTC, merged