added service
Inunor/internship pull request #140
Opened 2021-08-06 11:26 UTC by NurmukhammadMakhmudov

2021-08-06 12:27 UTC, RomPavel commented on src/app/models/admin-profile/admin-profile.component.ts
> +import { ServiceComponent } from './service/service.component';
do you need this

2021-08-06 12:28 UTC, RomPavel commented on src/assets/adminLocalStorage.json
> +[
its should be in mocks not assets

2021-08-06 12:28 UTC, RomPavel commented on src/app/models/admin-profile/service/service.component.ts
> +    // @ts-ignore
remove this

2021-08-06 12:29 UTC, RomPavel commented on src/app/models/admin-profile/service/service.component.ts
> +export class ServiceComponent {
ServiceComponent naming is too abstract, and its not a component

2021-08-06 12:30 UTC, RomPavel commented on src/app/models/admin-profile/service/service.component.ts
> +      .toPromise()
lets not promisify requests

2021-08-06 12:31 UTC, RomPavel commented on src/app/models/admin-profile/service/service.component.ts
> +    return this.http.get<TestData[]>(URL);
in our approach, we need to have store service as well
check auth-store.service or test-store.service

2021-08-06 12:32 UTC, RomPavel commented on src/app/models/admin-profile/admin-table/table.component.ts
> +      this.dataPrototype = this.notAssignedTests;
dataPrototype is super unclear naming

2021-08-06 14:19 UTC, Inunor requested changes

2021-08-06 14:19 UTC, Inunor commented on src/app/models/admin-profile/service/service.component.ts
> +export class ServiceComponent {
function naming as well, I think getTests would be much better then getData. Data doesn't give any information -> data is everything and nothing)

2021-08-08 16:41 UTC, ExxZzyy commented on src/app/models/admin-profile/admin-profile.component.ts
> +      console.log(data);
Remove console.log

2021-08-08 16:41 UTC, ExxZzyy commented on src/app/models/admin-profile/service/service.component.ts
> +    console.log(this.http.get<TestData[]>(URL));
Remove console.log

2021-08-08 18:04 UTC, ExxZzyy approved these changes

2021-08-08 18:06 UTC, shuliakleonid approved these changes

2021-08-08 19:47 UTC, merged