Feature/coach check service
Inunor/internship pull request #141
Opened 2021-08-06 14:57 UTC by ExxZzyy

Feature/coach check service

2021-08-06 16:05 UTC, RomPavel commented on src/app/models/coach-profile/coach-profile.module.ts
> +    MatProgressSpinnerModule,
do you need this?

2021-08-06 16:06 UTC, RomPavel commented on src/app/models/coach-profile/coach-profile.component.ts
>        [CoachTestTabs.unchecked]: MOCK_TESTS.filter((test) => !test.isChecked),
why you still need mocks here?

2021-08-06 16:08 UTC, RomPavel commented on src/app/models/coach-profile/coach-profile-table/coach-profile-table.component.html
> -  <table mat-table [dataSource]="dataSource" matSort matSortActive="date" matSortStart="asc">
how you use dataSource in component then?

2021-08-07 12:15 UTC, ExxZzyy commented on src/app/models/coach-profile/coach-profile.module.ts
> +    MatProgressSpinnerModule,
Yes, for this
![image](https://user-images.githubusercontent.com/66119764/128599802-9e05da27-3cbd-4e29-bb31-bd68eb329530.png)

2021-08-07 12:17 UTC, ExxZzyy commented on src/app/models/coach-profile/coach-profile.component.ts
>        [CoachTestTabs.unchecked]: MOCK_TESTS.filter((test) => !test.isChecked),
done
f3c1edc927ccaac75f32224f68afffbadcb79e6b

2021-08-07 12:17 UTC, ExxZzyy commented on src/app/models/coach-profile/coach-profile-table/coach-profile-table.component.html
> -  <table mat-table [dataSource]="dataSource" matSort matSortActive="date" matSortStart="asc">
done
f3c1edc927ccaac75f32224f68afffbadcb79e6b

2021-08-07 12:33 UTC, RomPavel commented on src/app/models/coach-profile/coach-profile-table/coach-profile-table.component.ts
> +    // this.dataSource = new MatTableDataSource(this.results);
remove this

2021-08-07 12:36 UTC, RomPavel commented on src/app/models/coach-profile/coach-profile.component.ts
>        [CoachTestTabs.unchecked]: MOCK_TESTS.filter((test) => !test.isChecked),
I dont understand, you have mocks for **this.tables** and for **this.results$**, why you need both of them?

2021-08-07 12:37 UTC, RomPavel commented on src/app/models/coach-profile/service/coach-tests-store.service.ts
> +    this.authStoreService.activeUser$
Why you need to wait for active user here?

2021-08-07 12:38 UTC, RomPavel commented on src/app/models/coach-profile/service/coach-tests-store.service.ts
> +    this.authStoreService.activeUser$
same here

2021-08-07 12:38 UTC, RomPavel commented on src/app/models/coach-profile/service/coach-tests-store.service.ts
> +    this.authStoreService.activeUser$
same here

2021-08-07 12:40 UTC, RomPavel commented on src/app/models/coach-profile/service/get-coach-tests-http.service.ts
> +  date: Date;
are you sure that backend return Date object to us?

2021-08-07 12:47 UTC, RomPavel commented on src/app/models/coach-profile/coach-profile.module.ts
> +    MatProgressSpinnerModule,
Do you really think we need 2nd spinner?
Yours spinner just spin infinitely, even when request is done, while 1st spinner only spin while making request 
![image](https://user-images.githubusercontent.com/31888768/128600557-9a1a2d69-9bac-4f10-a3ed-ca4e8d25fbf9.png)

2021-08-07 14:47 UTC, ExxZzyy commented on src/app/models/coach-profile/coach-profile.module.ts
> +    MatProgressSpinnerModule,
Delete it b6aebad9c2c3ea2c4d560dcc67d65c872c630642

2021-08-07 14:47 UTC, ExxZzyy commented on src/app/models/coach-profile/coach-profile.component.ts
>        [CoachTestTabs.unchecked]: MOCK_TESTS.filter((test) => !test.isChecked),
Remove mocks from results$ b6aebad9c2c3ea2c4d560dcc67d65c872c630642

2021-08-07 14:47 UTC, ExxZzyy commented on src/app/models/coach-profile/coach-profile-table/coach-profile-table.component.ts
> +    // this.dataSource = new MatTableDataSource(this.results);
Done b6aebad9c2c3ea2c4d560dcc67d65c872c630642

2021-08-07 14:47 UTC, ExxZzyy commented on src/app/models/coach-profile/service/coach-tests-store.service.ts
> +    this.authStoreService.activeUser$
Don't need, remove b6aebad9c2c3ea2c4d560dcc67d65c872c630642

2021-08-07 14:48 UTC, ExxZzyy commented on src/app/models/coach-profile/service/coach-tests-store.service.ts
> +    this.authStoreService.activeUser$
Don't need, remove b6aebad9c2c3ea2c4d560dcc67d65c872c630642

2021-08-07 14:48 UTC, ExxZzyy commented on src/app/models/coach-profile/service/coach-tests-store.service.ts
> +    this.authStoreService.activeUser$
Don't need, remove b6aebad9c2c3ea2c4d560dcc67d65c872c630642

2021-08-07 14:48 UTC, ExxZzyy commented on src/app/models/coach-profile/service/get-coach-tests-http.service.ts
> +  date: Date;
Change to string  b6aebad9c2c3ea2c4d560dcc67d65c872c630642

2021-08-07 15:16 UTC, RomPavel commented on src/app/models/coach-profile/service/coach-tests-store.service.ts
> +    this.coachTestResults$
Why you need this?)

2021-08-07 19:57 UTC, ExxZzyy commented on src/app/models/coach-profile/service/coach-tests-store.service.ts
> +    this.coachTestResults$
You mean getCoachCheckedTestResults function?

2021-08-07 19:59 UTC, RomPavel commented on src/app/models/coach-profile/service/coach-tests-store.service.ts
> +    this.coachTestResults$
I mean wait for this.coachTestResults$ in all functions

2021-08-08 11:51 UTC, ExxZzyy commented on src/app/models/coach-profile/service/coach-tests-store.service.ts
> +    this.coachTestResults$
Done 
348ac75c0b0280e6ab0768fcea8f76bd0b04f690

2021-08-08 13:32 UTC, shuliakleonid requested changes

2021-08-08 13:32 UTC, shuliakleonid commented on src/app/models/coach-profile/service/get-coach-tests-http.service.ts
> +
Interface must be in another folder, for example interfaces

2021-08-08 13:34 UTC, shuliakleonid requested changes

2021-08-08 13:34 UTC, shuliakleonid commented on src/app/models/coach-profile/service/get-coach-tests-http.service.ts
> +}
Interface must be in another folder, for example interfaces

2021-08-08 13:35 UTC, shuliakleonid requested changes

2021-08-08 13:35 UTC, shuliakleonid commented on src/app/models/coach-profile/service/get-coach-tests-http.service.ts
> +  level: string;
Interface must be in another folder, for example interfaces

2021-08-08 13:56 UTC, ExxZzyy commented on src/app/models/coach-profile/service/get-coach-tests-http.service.ts
> +  level: string;
Done
f629f6e82a3497ccf39cbc5e62f1daf69638aaf0

2021-08-08 13:59 UTC, shuliakleonid approved these changes

2021-08-08 14:05 UTC, merged