add HR can view test results of other users
Inunor/internship pull request #154
Opened 2021-08-11 15:27 UTC by casterweb

2021-08-11 15:30 UTC, casterweb commented
![Анимация](https://user-images.githubusercontent.com/54542430/129058360-6fc570fb-602d-41b7-a2f7-ba99e5771693.gif)

2021-08-11 18:27 UTC, shuliakleonid requested changes

2021-08-11 18:27 UTC, shuliakleonid commented on src/app/models/dialog-module/user-results-dialog/user-results-dialog.component.ts
>    constructor(
why you need that

2021-08-11 19:44 UTC, shuliakleonid approved these changes

2021-08-12 08:24 UTC, tanyushanel approved these changes

2021-08-12 10:31 UTC, merged