Finish test modal
Inunor/internship pull request #158
Opened 2021-08-13 11:23 UTC by dimahalaiskiy

<img width="1440" alt="Screenshot 2021-08-13 at 14 23 05" src="https://user-images.githubusercontent.com/74025448/129350140-0fd7f9aa-e175-4efd-8def-7c1b74cfe31c.png">

2021-08-13 11:24 UTC, dimahalaiskiy commented
Deleted sidebar scroll, add modal window

2021-08-15 12:20 UTC, shuliakleonid requested changes

2021-08-15 12:20 UTC, shuliakleonid commented on src/app/models/finish-test-modal/finish-test.component.ts
> +  constructor(
Can we add type to dialog

2021-08-15 12:20 UTC, shuliakleonid commented on src/app/models/finish-test-modal/finish-test.module.ts
> +export class FinishTestModule {}
do you remember that we have module with material component

2021-08-15 21:18 UTC, shuliakleonid approved these changes

2021-08-15 21:19 UTC, casterweb approved these changes

2021-08-15 21:20 UTC, merged