Feature/admin module
Inunor/internship pull request #168
Opened 2021-08-17 13:24 UTC by NurmukhammadMakhmudov

2021-08-17 13:28 UTC, ExxZzyy commented on src/app/models/admin-profile/admin-dialog/admin-dialog.component.ts
> +    @Inject(MAT_DIALOG_DATA) public data: any,
Don't use any

2021-08-17 13:32 UTC, ExxZzyy commented on src/mocks/admin-profile-utils.mock.ts
>  export interface CoachData {
Move this interfaces into src/app/interfaces

2021-08-17 15:53 UTC, tsiananel requested changes

2021-08-17 15:53 UTC, tsiananel commented on src/app/models/admin-profile/admin-table/table.component.scss
> +  margin: 0 50px;
Let use rem

2021-08-17 15:53 UTC, tsiananel commented on src/app/models/admin-profile/admin-table/table.component.ts
> +import { MatTable } from '@angular/material/table';
All material components move to angular-material-common.module

2021-08-17 20:10 UTC, shuliakleonid requested changes

2021-08-17 20:10 UTC, shuliakleonid commented on src/app/models/admin-profile/admin-table/table.component.ts
> +  constructor(public dialog: MatDialog, private service: AdminTableStoreService) {}
I think we have double code and better do this with enum object

2021-08-17 20:10 UTC, shuliakleonid commented on src/app/models/admin-profile/admin-table/table.component.ts
> +      this.assignedData = assignedData.results;
remove console.log

2021-08-17 20:10 UTC, shuliakleonid commented on src/app/services/adminTableData.service.ts
>      );
we have variable for URL address

2021-08-17 20:10 UTC, shuliakleonid commented on src/app/services/adminTableData.service.ts
> +
use const BASE_API_URL

2021-08-17 20:10 UTC, shuliakleonid commented on src/app/services/adminTableData.service.ts
> +      data,
same

2021-08-17 20:10 UTC, shuliakleonid commented on src/app/services/store/adminTableStore.service.ts
>    }
remove console.log

2021-08-24 07:02 UTC, RomPavel approved these changes

2021-08-24 07:18 UTC, merged