Feature/results page layout
Inunor/internship pull request #170
Opened 2021-08-18 16:27 UTC by tsiananel

![image](https://user-images.githubusercontent.com/60880817/129935872-a1116d23-1c13-464a-b25f-e80322493ade.png)

2021-08-18 16:36 UTC, shuliakleonid requested changes

2021-08-18 16:36 UTC, shuliakleonid commented on src/app/models/result/result.component.html
> +</div>
use enum Route

2021-08-18 16:36 UTC, shuliakleonid commented on src/app/services/store/test-store.service.ts
>      );
it possible rewrite

2021-08-18 17:09 UTC, RomPavel commented on src/app/models/common-test/common-test.component.html
> -    <app-proceed-buttons
Did you discuss this change with BA?

2021-08-18 17:17 UTC, tsiananel commented on src/app/models/common-test/common-test.component.html
> -    <app-proceed-buttons
Yes, it's for delete(

2021-08-19 09:59 UTC, shuliakleonid approved these changes

2021-08-19 12:28 UTC, merged