genarate-module-component
Inunor/internship pull request #28
Opened 2021-07-07 22:24 UTC by dimahalaiskiy

2021-07-07 22:42 UTC, RomPavel commented on exadel-trainee-app/src/app/models/speaking/speaking.component.ts
> +export class SpeakingComponent implements OnInit {
You can see that @shuliakleonid in his PR named grammar test page (which is one of step of test as yours) as grammar-test, so its better to have common naming style.
So its better to change speaking to speaking test everywhere

2021-07-07 22:44 UTC, RomPavel commented
You trying to add file, which is pretty huge and its not needed in repository

![image](https://user-images.githubusercontent.com/31888768/124837657-ef1d7500-df8d-11eb-96fe-07d0cb92fb5f.png)

2021-07-07 22:59 UTC, RomPavel commented on exadel-trainee-app/src/app/app.module.ts
> +  imports: [BrowserModule, LoginModule, SpeakingModule, AppRoutingModule, BrowserAnimationsModule],
**SpeakingModule** should not be included into main module.

2021-07-08 05:34 UTC, Inunor commented on exadel-trainee-app/angular.json
> +  "cli": {
What is it?)

2021-07-08 05:52 UTC, Inunor requested changes

2021-07-08 05:52 UTC, Inunor commented on exadel-trainee-app/src/app/models/speaking/speaking-routing.module.ts
> +    path: 'speaking',
should be just ''

2021-07-10 08:35 UTC, closed without merging