user-profile-module added
Inunor/internship pull request #40
Opened 2021-07-08 18:50 UTC by tanyushanel

2021-07-08 19:13 UTC, RomPavel commented on exadel-trainee-app/src/app/app-routing.module.ts
> +    loadChildren: () => import('./models/user/user.module').then((m) => m.UserModule),
I see @casterweb in his PR use **hr-profile** for naming everywhere. 
Could you please use **-profile** everywhere in your code
You can leave **path** as **user**, I think we will rename some pathes in future

2021-07-08 22:05 UTC, RomPavel commented
Sorry If I didnt explain it well.
I mean if you have file/folder name with few words, please use 'my-file-name.ts' naming style
But in code use 'myFileName' style

2021-07-09 10:52 UTC, Inunor requested changes

2021-07-09 10:52 UTC, Inunor commented on exadel-trainee-app/src/app/models/user-profile/user-profile.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
I think you can delete test files (or don't generate them at all, check angular ng generate flags for more info)

2021-07-09 10:52 UTC, Inunor commented on exadel-trainee-app/src/app/app.module.ts
> +  declarations: [AppComponent, UserProfileComponent],
You shouldn't register your component here, you should move it to your module

2021-07-09 22:02 UTC, RomPavel approved these changes

2021-07-10 09:43 UTC, Inunor approved these changes

2021-07-12 14:01 UTC, merged