Add services to sidebar
Inunor/internship pull request #73
Opened 2021-07-14 10:35 UTC by shuliakleonid

add user name title
add services for Http requiest

2021-07-14 10:36 UTC, shuliakleonid commented on exadel-trainee-app/package.json
> +    "lint:styles": "stylelint \"src/**/*.scss\" --fix"
fix stylelint error when start pre-commit

2021-07-14 10:37 UTC, shuliakleonid commented on exadel-trainee-app/package.json
> +      "npm run lint:styles",
fix husly pre-commit

2021-07-15 05:27 UTC, Inunor requested changes

2021-07-15 05:27 UTC, Inunor commented on exadel-trainee-app/src/interfaces/user.interfaces.ts
> +  roles: string[];
I think the role should be an array of Roles interfaces or something, not just string array

2021-07-15 05:27 UTC, Inunor commented on exadel-trainee-app/src/constants/mock-user-data.ts
> +    roles: ['coach'],
Same here about roles, could you please tell me why did you decide to make it just array of strings?

2021-07-15 05:27 UTC, Inunor commented on exadel-trainee-app/src/app/services/user-role.service.ts
> +      this.activeUser = user;
It's ok, but in ngrx (redux) world and in javascript world in general it's a good practice to copy objects, not just copy link.`this.activeUser = { ...user }`

2021-07-15 05:27 UTC, Inunor commented on exadel-trainee-app/src/app/services/user-role.service.ts
> +      this.activeUser = user;
Everything else on services is done well from your side

2021-07-15 05:27 UTC, Inunor commented on exadel-trainee-app/src/app/services/user-role.service.ts
> +export class UserRoleService {
I would suggest having a common name for these store services across app. You will have a bunch of store services, so something like [Feature]StoreService will be enough (UsersStoreService, RoleStoreService)

2021-07-15 06:08 UTC, shuliakleonid commented on exadel-trainee-app/src/constants/mock-user-data.ts
> +    roles: ['coach'],
It`s answer for request API

2021-07-15 06:11 UTC, shuliakleonid commented on exadel-trainee-app/src/app/services/user-role.service.ts
> +      this.activeUser = user;
Done, https://github.com/Inunor/internship/pull/73

2021-07-15 06:23 UTC, shuliakleonid commented on exadel-trainee-app/src/app/services/user-role.service.ts
> +export class UserRoleService {
Done, like that 
![image](https://user-images.githubusercontent.com/70269636/125738915-30a947e3-9256-4db2-883e-3cd605b949a1.png)
https://github.com/Inunor/internship/pull/73

2021-07-15 07:52 UTC, shuliakleonid commented on exadel-trainee-app/src/interfaces/user.interfaces.ts
> +  roles: string[];
I ask the backend developer for the structure of  request and answer is :
![image](https://user-images.githubusercontent.com/70269636/125737325-bb3afd40-30bd-4ad3-bbfd-26ee4ec9e469.png)

2021-07-16 08:39 UTC, Inunor approved these changes

2021-07-16 08:49 UTC, merged