Speaking test module
Inunor/internship pull request #92
Opened 2021-07-16 21:41 UTC by dimahalaiskiy

2021-07-16 22:16 UTC, dimahalaiskiy commented
audio-recorder

2021-07-16 22:28 UTC, RomPavel commented on exadel-trainee-app/src/app/models/speaking-test/speaking-test.component.html
> +    {{ isRecording == false ? 'Start Recording' : 'Stop Recording' }}
you can simple use **!isRecording ? 'Start Recording' : 'Stop Recording'**

2021-07-18 14:24 UTC, Inunor requested changes

2021-07-18 14:24 UTC, Inunor commented on exadel-trainee-app/src/app/models/speaking-test/speaking-test.module.ts
> +  imports: [SpeakingTestRoutingModule, CommonModule, FormsModule, MatButtonModule, MatCardModule],
You should use https://github.com/Inunor/internship/blob/dev/exadel-trainee-app/src/app/models/angular-material-common.module.ts. Someone already created it, it exports all the necessary angular material modules

2021-07-18 14:24 UTC, Inunor commented on exadel-trainee-app/src/app/models/speaking-test/speaking-test.component.ts
> +    if (this.isRecording === true) {
You can use just if (this.isRecording)

2021-07-18 19:18 UTC, RomPavel commented on exadel-trainee-app/src/app/models/speaking-test/speaking-test.component.ts
> +    return this.isRecording === false ? 'primary' : 'warn';
!this.isRecording

2021-07-18 19:58 UTC, RomPavel approved these changes

2021-07-18 20:07 UTC, RomPavel approved these changes

2021-07-18 20:10 UTC, merged