Feature/admin module
Inunor/internship pull request #97
Opened 2021-07-19 06:25 UTC by NurmukhammadMakhmudov

![image](https://user-images.githubusercontent.com/80941197/126112492-7a9fdbdc-4900-47ed-8c7a-a04bc35601b3.png)
![image](https://user-images.githubusercontent.com/80941197/126112535-49b406fd-bf07-464f-b8dc-c12fdf4b5378.png)
![image](https://user-images.githubusercontent.com/80941197/126112557-09f75ce2-3a23-406a-a699-246798f5b854.png)
 

changed the style added new table add part of logic

2021-07-19 23:11 UTC, RomPavel commented
Change target branch to dev, its hard to review 120 files

2021-07-20 14:24 UTC, NurmukhammadMakhmudov commented
done

2021-07-20 14:51 UTC, RomPavel commented on exadel-trainee-app/src/app/models/admin-profile/admin-profile.component.ts
> +export interface SelectedValue {
Lets import it from admin-dialog.component

2021-07-20 14:51 UTC, RomPavel commented on exadel-trainee-app/src/app/models/admin-profile/admin-profile.component.ts
> +      console.log(this.dataSource[result.position]);
please remove console.logs and comments

2021-07-20 14:53 UTC, Inunor requested changes

2021-07-20 14:53 UTC, Inunor commented on exadel-trainee-app/src/app/models/admin-profile/admin-dialog/admin-dialog.component.ts
> +export interface SelectedValue {
Please change this interface name. Interface name should have some meaningful name). Same for data inside the constructor. data: SelectedValue doesn't give me almost any information about data structure

2021-07-20 14:53 UTC, Inunor commented on exadel-trainee-app/src/app/models/admin-profile/admin-profile.component.html
> +  <div *ngIf="AssignSelector === '0'">
As I see these tables look almost the same, could you somehow refactor them? I dunno create table component for it and reuse or something like that

2021-07-20 14:53 UTC, Inunor commented on exadel-trainee-app/src/app/models/admin-profile/admin-profile.component.ts
> +export interface SelectedValue {
The same about this interface (Aren't these interfaces the same?)

2021-07-20 14:53 UTC, RomPavel commented on exadel-trainee-app/src/app/models/admin-profile/admin-profile.component.ts
> +  onClickAssigned(): void {
3 function, doing same thing, let have one onTabChange(selector: string)

2021-07-20 14:54 UTC, RomPavel commented on exadel-trainee-app/src/mocks/admin-profile-utils.mock.ts
> +  'Not assign',
it better to have this info in a separate property like isAssigned: true

2021-07-22 16:24 UTC, Inunor commented
Any updates?

2021-07-22 17:00 UTC, NurmukhammadMakhmudov commented on exadel-trainee-app/src/app/models/admin-profile/admin-profile.component.html
> +  <div *ngIf="AssignSelector === '0'">
will do it in the weekend

2021-07-22 17:06 UTC, NurmukhammadMakhmudov commented
https://user-images.githubusercontent.com/80941197/126679672-6004a1b4-2e43-404f-8c61-64ba64b85a5c.mov

2021-07-22 17:13 UTC, RomPavel commented
Can you somehow by default not show coach avatar and coach info

2021-07-22 17:21 UTC, RomPavel commented on exadel-trainee-app/src/app/models/admin-profile/admin-profile.component.ts
> +          this.isAssignTrueArray.reverse();
Those 3 lines can be done with **array.unshift**

2021-07-22 17:23 UTC, RomPavel commented on exadel-trainee-app/src/app/models/admin-profile/admin-profile.component.ts
> +        this.dataSource.data[result.position].coach = result.coach;
lets put **this.dataSource.data[result.position]** in a separate **const assignedTest**

2021-07-22 17:24 UTC, RomPavel commented on exadel-trainee-app/src/app/models/admin-profile/admin-profile.component.ts
> +  isAssignTrueArray: TestData[] = [];
Let change naming to **assignedTests** and **notAssignedTests**

2021-07-25 19:28 UTC, RomPavel commented on src/app/models/admin-profile/admin-profile-routing.ts
> -import { UserRole } from '../../../constants/data-constants';
Please, revert this change

2021-07-25 19:31 UTC, RomPavel commented on .prettierignore
> -src/assets/**
Please, return this file

2021-07-25 19:32 UTC, RomPavel commented on src/app/models/admin-profile/admin-profile.component.ts
> +      try {
Why do you need try catch here

2021-07-25 19:35 UTC, RomPavel commented on src/app/models/admin-profile/admin-dialog/admin-dialog.component.html
> +          dataSource[data.position].isAssign
Let put this logic in method in component

2021-07-25 19:35 UTC, RomPavel commented on src/app/models/admin-profile/admin-dialog/admin-dialog.component.html
> +          dataSource[data.position].isAssign
Let put this logic in method in component getSelectedCoachPhoneNumber

2021-07-25 19:35 UTC, RomPavel commented on src/app/models/admin-profile/admin-dialog/admin-dialog.component.html
> +          dataSource[data.position].isAssign
Let put this logic in method in component **getSelectedCoachEmail**

2021-07-26 05:59 UTC, NurmukhammadMakhmudov commented on src/app/models/admin-profile/admin-profile.component.ts
> +      try {
there is a cancel button in dialog window which returns null | undefined, so catch this

2021-07-26 06:37 UTC, RomPavel commented on src/app/models/admin-profile/admin-profile.component.ts
> +      try {
Its not an option. 
Your code should not throw errors on some basic user actions.
Just add **if(!result) { return }**

2021-07-26 06:50 UTC, RomPavel commented on src/app/models/admin-profile/admin-profile.component.ts
> +      data: { position: value - 1, coach: '--' },
Could you please explain why you need this magic string '--' and also how it works, because from modal interface I see that modal expect coach as object

2021-07-26 06:54 UTC, RomPavel commented on src/app/models/admin-profile/admin-dialog/admin-dialog.component.ts
why you store whole tests array in modal for just one test?
you need to pass selected test for modal through MAT_DIALOG_DATA

2021-07-26 07:09 UTC, NurmukhammadMakhmudov commented on src/app/models/admin-profile/admin-profile.component.ts
> +      data: { position: value - 1, coach: '--' },
it was added when I tried to insert dialog window and then forgot about it, sorry my fault

2021-07-26 08:18 UTC, NurmukhammadMakhmudov commented on src/app/models/admin-profile/admin-profile.component.ts
> +      data: { position: value - 1, coach: '--' },
if i delete it dialog do not work

2021-07-26 08:23 UTC, NurmukhammadMakhmudov commented on src/app/models/admin-profile/admin-dialog/admin-dialog.component.ts
Do you mean why I am using dataSource or ?
I pass only position value and use it like id to get coach name from array

2021-07-28 07:38 UTC, RomPavel approved these changes

2021-07-28 12:50 UTC, Inunor approved these changes

2021-07-28 12:54 UTC, merged